app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(topmods = "data")
app$snapshot()
app$snapshot()
app$setInputs(topmods = "distributions")
app$snapshot()
app$setInputs(topmods = "model")
app$snapshot()
app$setInputs(topmods = "module")
app$setInputs(lev2 = "TOTALVAE")
app$snapshot()
app$setInputs(curmod = "scanpy")
app$snapshot()
app$setInputs(topmods = "pp")
app$snapshot()
app$setInputs(lev2 = "log1p")
app$snapshot()
